export const ALL_ZONES = [
  { key: "AMRITSAR ZO", label: "Amritsar" },
  { key: "BAREILLY ZO", label: "Bareilly" },
  { key: "BHATINDA ZO", label: "Bhatinda" },
  { key: "BHOPAL ZO", label: "Bhopal" },
  { key: "CHANDIGARH ZO", label: "Chandigarh" },
  { key: "CHENNAI ZO", label: "Chennai" },
  { key: "DEHRADUN ZO", label: "Dehradun" },
  { key: "DELHI- I ZO", label: "Delhi I" },
  { key: "DELHI- II ZO", label: "Delhi II" },
  { key: "FARIDKOT ZO", label: "Faridkot" },
  { key: "GANDHINAGAR ZO", label: "Gandhinagar" },
  { key: "GURDASPUR ZO", label: "Gurdaspur" },
  { key: "GURUGRAM ZO", label: "Gurugram" },
  { key: "GUWAHATI ZO", label: "Guwahati" },
  { key: "HOSHIARPUR ZO", label: "Hoshiarpur" },
  { key: "JAIPUR ZO", label: "Jaipur" },
  { key: "JALANDHAR ZO", label: "Jalandhar" },
  { key: "KOLKATA ZO", label: "Kolkata" },
  { key: "LUCKNOW ZO", label: "Lucknow" },
  { key: "LUDHIANA ZO", label: "Ludhiana" },
  { key: "MUMBAI ZO", label: "Mumbai" },
  { key: "NOIDA ZO", label: "Noida" },
  { key: "PANCHKULA ZO", label: "Panchkula" },
  { key: "PATIALA ZO", label: "Patiala" },
  { key: "VIJAYAWADA ZO", label: "Vijayawada" },
  { key: "HEAD OFFICE", label: "Head Office" },
] as const